### ISSUE TITLE
cannot install - credentials missing

### ISSUE THREAD

**Issue by grandrea** [marseille-proteomique/DIAgui#2]
Hello, after running 

if(!requireNamespace("devtools", quietly = TRUE)){
  install.packages("devtools") 
}
devtools::install_github("marseille-proteomique/DIAgui")

I get the error

> devtools::install_github("marseille-proteomique/DIAgui")
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 57/60
  Rate limit reset at: 2024-06-17 22:35:40 UTC

any clues?

**Comment by SamGG** [comment]
Hi. Thanks for your interest in the package.
Could you explain in a few words how you solve this problem?
Best, Samuel
