### ISSUE TITLE
New feature: filter peptides by quantity.quality>0.8

### ISSUE THREAD

**Issue by SamGG** [marseille-proteomique/DIAgui#4]
From Jérôme V.

> I would like to ask for a parameter:
> 
> Could we filter peptides by quantity.quality>0.8?
> 
> On the QuantUMS version, this is the main criterion for me, to filter on data quality.

**Comment by mgerault** [comment]
Possibility has now been added on the version 1.4.3 of DIAgui.

**Comment by mgerault** [comment]
Possibility has now been added on the version 1.4.3 of DIAgui.
