### ISSUE TITLE
"keep only proteotypic peptides" question

### ISSUE THREAD

**Issue by bluemooninvestor** [marseille-proteomique/DIAgui#6]
Hi

Thank you for creating this nice tool. I was wondering what happens when I use the "keep only proteotypic peptides" option on the "Protein Groups". Once, I use this option, the protein groups essentially become unique proteins? Am I assuming this correctly?

Thanks

**Comment by mgerault** [comment]
Hello,

No this filter is on the peptide. When computing the quantification for the protein groups, DIAgui apply first some filters on the selected p-values to remove some of the precursors from the quantification. Then, if you select the criterion "keep only proteotypic peptides", it will remove peptides that are shared with other proteins keeping only the unique peptides for the calculation of the quantification. 
In this way, the quantification is more stringent, assuring that each identified peptides actually belong to the identified protein.

I hope this help; I'll wait a week before closing the question.
